import fs from "fs";
import path from "path";
import config from "./config.json" with { type: "json" };

export async function runFixer(scan: any) {
  const fixes: string[] = [];

  // ----------------------------------------------------
  // 1) إصلاح imports المكسورة
  // ----------------------------------------------------
  if (config.fixer.fixBrokenImports) {
    for (const broken of scan.brokenImports) {
      const [file, importPath] = broken.split("→").map((s: string) => s.trim());

      const fixedPath = tryFixImportPath(file, importPath);

      if (fixedPath) {
        applyImportFix(file, importPath, fixedPath);
        fixes.push(`Fixed import in ${file}: ${importPath} → ${fixedPath}`);
      } else {
        fixes.push(`⚠ Could not fix import: ${file} → ${importPath}`);
      }
    }
  }

  // ----------------------------------------------------
  // 2) إنشاء الملفات الناقصة
  // ----------------------------------------------------
  if (config.fixer.createMissingDirectories) {
    for (const missing of scan.missingFiles) {
      const fullPath = resolveMissingFile(missing);

      if (!fs.existsSync(fullPath)) {
        fs.mkdirSync(path.dirname(fullPath), { recursive: true });
        fs.writeFileSync(fullPath, generatePlaceholder(missing));
        fixes.push(`Created missing file: ${fullPath}`);
      }
    }
  }

  // ----------------------------------------------------
  // 3) إصلاح tsconfig.json
  // ----------------------------------------------------
  if (config.fixer.fixTSConfigPaths) {
    fixTSConfig(fixes);
  }

  // ----------------------------------------------------
  // 4) إصلاح next.config.js
  // ----------------------------------------------------
  if (config.fixer.fixNextConfig) {
    fixNextConfig(fixes);
  }

  // ----------------------------------------------------
  // 5) إصلاح صفحات Next.js
  // ----------------------------------------------------
  fixNextPages(scan, fixes);

  // ----------------------------------------------------
  // 6) إصلاح API routes
  // ----------------------------------------------------
  fixApiRoutes(scan, fixes);

  // ----------------------------------------------------
  // 7) إصلاح server/client boundaries
  // ----------------------------------------------------
  fixServerClientViolations(scan, fixes);

  // ----------------------------------------------------
  // 8) إصلاح naming conventions
  // ----------------------------------------------------
  fixNamingConventions(scan, fixes);

  return fixes;
}

// ----------------------------------------------------
// إصلاح مسار import
// ----------------------------------------------------
function tryFixImportPath(currentFile: string, importPath: string) {
  if (importPath.startsWith("@")) return null;

  if (importPath.startsWith(".")) {
    const normalized = path
      .normalize(path.join(path.dirname(currentFile), importPath))
      .replace(process.cwd(), "")
      .replace(/\\/g, "/")
      .replace(/^\/src\//, "");

    return `@/${normalized}`;
  }

  return null;
}

// ----------------------------------------------------
// تطبيق إصلاح import داخل الملف
// ----------------------------------------------------
function applyImportFix(file: string, oldPath: string, newPath: string) {
  const content = fs.readFileSync(file, "utf8");
  const updated = content.replace(`"${oldPath}"`, `"${newPath}"`);
  fs.writeFileSync(file, updated);
}

// ----------------------------------------------------
// إنشاء ملف ناقص
// ----------------------------------------------------
function resolveMissingFile(importPath: string) {
  const clean = importPath.replace(/^@\//, "src/");
  return path.join(process.cwd(), clean + ".ts");
}

// ----------------------------------------------------
// placeholder
// ----------------------------------------------------
function generatePlaceholder(name: string) {
  return `// Auto-generated by A3MALY ENGINE
export default function placeholder() { return null; }
`;
}

// ----------------------------------------------------
// إصلاح tsconfig.json
// ----------------------------------------------------
function fixTSConfig(fixes: string[]) {
  const tsconfigPath = path.join(process.cwd(), "tsconfig.json");

  if (!fs.existsSync(tsconfigPath)) return;

  const tsconfig = JSON.parse(fs.readFileSync(tsconfigPath, "utf8"));

  tsconfig.compilerOptions = tsconfig.compilerOptions || {};
  tsconfig.compilerOptions.paths = tsconfig.compilerOptions.paths || {};

  if (!tsconfig.compilerOptions.paths["@/*"]) {
    tsconfig.compilerOptions.paths["@/*"] = ["src/*"];
    fixes.push("Added @ alias to tsconfig.json");
  }

  fs.writeFileSync(tsconfigPath, JSON.stringify(tsconfig, null, 2));
}

// ----------------------------------------------------
// إصلاح next.config.js
// ----------------------------------------------------
function fixNextConfig(fixes: string[]) {
  const nextConfigPath = path.join(process.cwd(), "next.config.js");

  if (!fs.existsSync(nextConfigPath)) return;

  let content = fs.readFileSync(nextConfigPath, "utf8");

  if (content.includes("autoRepair")) {
    content = content.replace(/.*autoRepair.*\n?/g, "");
    fixes.push("Removed autoRepair from next.config.js");
  }

  fs.writeFileSync(nextConfigPath, content);
}

// ----------------------------------------------------
// إصلاح صفحات Next.js
// ----------------------------------------------------
function fixNextPages(scan: any, fixes: string[]) {
  for (const file of scan.nextErrors) {
    if (file.includes("page.tsx")) {
      const content = fs.readFileSync(file, "utf8");
      if (!content.includes("export default")) {
        fs.writeFileSync(
          file,
          content + `\n\nexport default function Page() { return <div />; }\n`
        );
        fixes.push(`Added default export to page: ${file}`);
      }
    }
  }
}

// ----------------------------------------------------
// إصلاح API routes
// ----------------------------------------------------
function fixApiRoutes(scan: any, fixes: string[]) {
  for (const file of scan.files) {
    if (file.endsWith("route.ts")) {
      const content = fs.readFileSync(file, "utf8");

      if (!content.includes("export async function GET")) {
        fs.writeFileSync(
          file,
          content +
            `\nexport async function GET() { return Response.json({ ok: true }); }\n`
        );
        fixes.push(`Added GET handler to API route: ${file}`);
      }
    }
  }
}

// ----------------------------------------------------
// إصلاح server/client violations
// ----------------------------------------------------
function fixServerClientViolations(scan: any, fixes: string[]) {
  for (const file of scan.files) {
    const content = fs.readFileSync(file, "utf8");

    if (content.includes("useState") && !content.includes('"use client"')) {
      const updated = `"use client"\n` + content;
      fs.writeFileSync(file, updated);
      fixes.push(`Added "use client" to component using useState: ${file}`);
    }
  }
}

// ----------------------------------------------------
// إصلاح naming conventions
// ----------------------------------------------------
function fixNamingConventions(scan: any, fixes: string[]) {
  for (const file of scan.files) {
    const base = path.basename(file);

    if (base.endsWith(".tsx") && /^[a-z]/.test(base)) {
      const newName = base[0].toUpperCase() + base.slice(1);
      const newPath = path.join(path.dirname(file), newName);

      fs.renameSync(file, newPath);
      fixes.push(`Renamed component to PascalCase: ${base} → ${newName}`);
    }
  }
}
