// Auto-generated by A3MALY ENGINE

export async function createCustomers(data: any) {
  return data;
}

export async function updateCustomers(id: string, data: any) {
  return data;
}

export async function deleteCustomers(id: string) {
  return true;
}
